'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import {
  Camera,
  X,
  Download,
  AlertTriangle,
  Loader2,
  Video,
  Share2,
  Ruler,
} from 'lucide-react';
import { useArSession } from '../useArSession';
import { prepareDesignForOverlay, type DesignSourceVerdict } from '@/services/ar/designSource';
import {
  checkClipSupport,
  compositeFrame,
  canvasToPngBlob,
  recordCanvasClip,
  downloadBlob,
  captureFilename,
  type ClipSupport,
  type OverlayTransform,
} from '@/services/ar/captureService';
import { shareCapture, buildShareText } from '@/services/ar/shareCapture';
import { resolveShareLink } from '../shareLink';
import PlacementGuides, {
  guideById,
  nextGuide,
  type PlacementGuideId,
} from './PlacementGuides';

/**
 * Live camera preview: point the phone at your skin, see the design on it.
 *
 * Deliberately NOT tracked. There is no body detection here and no fabricated
 * accuracy figure — the user positions the design themselves and what they see
 * is exactly what was composited. Body/limb tracking is a v2 concern (and no
 * library in this stack can do it today; see docs/adr/0021).
 *
 * Placement comes from the caller, which got it from intake. This component
 * never guesses which body part it is looking at. The opt-in placement guides
 * are rulers drawn on the glass, not claims about where the user's arm is.
 *
 * PRIVACY: camera frames never leave the device. Captures (still or clip) are
 * composited on a local canvas and exit only through the OS share sheet or a
 * download — both explicit user taps. See src/services/ar/captureService.ts.
 */

export interface ARMirrorDesign {
  id: string;
  /** Image URL of a design generated by the platform. */
  image: string;
  title?: string;
}

export interface ARMirrorProps {
  designs: ARMirrorDesign[];
  /** Placement tag resolved during intake. Displayed, never inferred. */
  placement?: string;
  /** Design to preselect in the tray — e.g. the one just picked in /design.
   *  Ignored when it isn't in `designs`. */
  initialSelectedId?: string;
  /** Funnel-forward URL (smart-match handoff). When set, the mirror offers
   *  "Find your artist" instead of leaving exit as the only door out. */
  findArtistHref?: string;
  onExit?: () => void;
}

/** Ink sinks into skin tone instead of floating like a sticker. */
const BLEND_MODE = 'multiply';

type OverlayState =
  | { kind: 'none' }
  | { kind: 'checking' }
  | {
      kind: 'ready';
      src: string;
      /** The stripped design pixels — the same canvas both captures composite. */
      canvas: HTMLCanvasElement;
      verdict: DesignSourceVerdict;
    }
  | { kind: 'blocked'; verdict: DesignSourceVerdict };

/** A capture that exists locally and is waiting for the user to send or save it. */
interface CapturedView {
  file: File;
  kind: 'still' | 'clip';
}

/** What happened after the send tap — each variant renders one honest line. */
type ShareNote =
  | { kind: 'shared' }
  | { kind: 'fallback'; linkCopied: boolean; hadLink: boolean }
  | { kind: 'error'; message: string };

export default function ARMirror({
  designs,
  placement,
  initialSelectedId,
  findArtistHref,
  onExit,
}: ARMirrorProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const captureCanvasRef = useRef<HTMLCanvasElement | null>(null);
  const stageRef = useRef<HTMLDivElement | null>(null);

  const session = useArSession(videoRef);

  const [selectedId, setSelectedId] = useState<string | null>(() =>
    initialSelectedId && designs.some((d) => d.id === initialSelectedId)
      ? initialSelectedId
      : null,
  );
  const [overlay, setOverlay] = useState<OverlayState>({ kind: 'none' });
  const [position, setPosition] = useState({ x: 50, y: 50 }); // percent of stage
  const [size, setSize] = useState(40); // percent of stage width
  const [rotation, setRotation] = useState(0);
  const [opacity, setOpacity] = useState(0.85);
  const dragRef = useRef<{ x: number; y: number } | null>(null);

  // Capture & share state.
  const [clipSupport, setClipSupport] = useState<ClipSupport | null>(null);
  const [recording, setRecording] = useState(false);
  const [captured, setCaptured] = useState<CapturedView | null>(null);
  const [captureError, setCaptureError] = useState<string | null>(null);
  const [sharing, setSharing] = useState(false);
  const [shareNote, setShareNote] = useState<ShareNote | null>(null);

  // Placement guide — opt-in, off by default.
  const [guide, setGuide] = useState<PlacementGuideId | null>(null);

  const selected = useMemo(
    () => designs.find((d) => d.id === selectedId) ?? null,
    [designs, selectedId],
  );

  // Clip recording is a browser fact, so it can only be checked after mount.
  useEffect(() => {
    setClipSupport(checkClipSupport());
  }, []);

  /**
   * Load the chosen design and run the on-skin guard before anything is drawn.
   * A design that fails the guard never produces a renderable source.
   */
  useEffect(() => {
    // A capture belongs to the design it was taken with; switching designs
    // (or deselecting) makes it stale, so it stops being offered.
    setCaptured(null);
    setShareNote(null);
    setCaptureError(null);

    if (!selected) {
      setOverlay({ kind: 'none' });
      return;
    }

    let cancelled = false;
    setOverlay({ kind: 'checking' });

    const img = new Image();
    // Needed so the pixels are readable; without it the guard cannot inspect
    // the image and correctly refuses to render it.
    img.crossOrigin = 'anonymous';

    img.onload = () => {
      if (cancelled) return;
      const { verdict, canvas } = prepareDesignForOverlay(img);
      if (!canvas) {
        setOverlay({ kind: 'blocked', verdict });
        return;
      }
      setOverlay({ kind: 'ready', src: canvas.toDataURL('image/png'), canvas, verdict });
    };

    img.onerror = () => {
      if (cancelled) return;
      setOverlay({
        kind: 'blocked',
        verdict: {
          usable: false,
          reason: 'unreadable-pixels',
          whiteBorderFraction: null,
          message:
            "This design's image could not be loaded, so it can't be checked or previewed. Try again, or use the photo preview instead.",
        },
      });
    };

    img.src = selected.image;
    return () => {
      cancelled = true;
    };
  }, [selected]);

  // Dragging the design around the stage.
  const onPointerDown = useCallback((e: React.PointerEvent) => {
    e.preventDefault();
    (e.target as Element).setPointerCapture?.(e.pointerId);
    dragRef.current = { x: e.clientX, y: e.clientY };
  }, []);

  const onPointerMove = useCallback((e: React.PointerEvent) => {
    if (!dragRef.current || !stageRef.current) return;
    const rect = stageRef.current.getBoundingClientRect();
    const dx = ((e.clientX - dragRef.current.x) / rect.width) * 100;
    const dy = ((e.clientY - dragRef.current.y) / rect.height) * 100;
    dragRef.current = { x: e.clientX, y: e.clientY };
    setPosition((p) => ({
      x: Math.max(0, Math.min(100, p.x + dx)),
      y: Math.max(0, Math.min(100, p.y + dy)),
    }));
  }, []);

  const onPointerUp = useCallback(() => {
    dragRef.current = null;
  }, []);

  const currentTransform = useCallback(
    (): OverlayTransform => ({
      x: position.x,
      y: position.y,
      size,
      rotation,
      opacity,
      blendMode: BLEND_MODE,
    }),
    [position, size, rotation, opacity],
  );

  /**
   * Prepare the hidden canvas at the video's native resolution and return
   * everything a capture needs, or null when the frame isn't ready.
   */
  const prepareCaptureCanvas = useCallback(() => {
    const video = videoRef.current;
    const canvas = captureCanvasRef.current;
    if (!video || !canvas || overlay.kind !== 'ready') return null;
    const w = video.videoWidth;
    const h = video.videoHeight;
    if (!w || !h) return null;
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext('2d');
    if (!ctx) return null;
    return { video, canvas, ctx, w, h, design: overlay.canvas };
  }, [overlay]);

  /** Flatten the current frame plus the overlay, exactly as shown. */
  const captureStill = useCallback(async () => {
    const prep = prepareCaptureCanvas();
    if (!prep) return;
    setCaptureError(null);
    setShareNote(null);
    try {
      compositeFrame(prep.ctx, prep.video, prep.w, prep.h, prep.design, currentTransform());
      const blob = await canvasToPngBlob(prep.canvas);
      const file = new File([blob], captureFilename('still', 'png'), { type: 'image/png' });
      setCaptured({ file, kind: 'still' });
    } catch {
      setCaptureError("that one didn't take. try the shot again.");
    }
  }, [prepareCaptureCanvas, currentTransform]);

  /** Three seconds of exactly what the mirror is showing. */
  const captureClip = useCallback(async () => {
    if (recording) return;
    const mime = clipSupport?.mime;
    const prep = prepareCaptureCanvas();
    if (!mime || !prep) return;

    setCaptureError(null);
    setShareNote(null);
    setRecording(true);

    // The transform is frozen at record start: the clip shows the placement
    // the user chose, not a hand that slipped mid-recording.
    const transform = currentTransform();
    const draw = () =>
      compositeFrame(prep.ctx, prep.video, prep.w, prep.h, prep.design, transform);
    draw();

    try {
      const blob = await recordCanvasClip(prep.canvas, mime, { onFrame: draw });
      const file = new File([blob], captureFilename('clip', mime.extension), {
        type: blob.type,
      });
      setCaptured({ file, kind: 'clip' });
    } catch (error) {
      setCaptureError(
        error instanceof Error ? error.message : 'Recording failed partway through. Try again.',
      );
    } finally {
      setRecording(false);
    }
  }, [recording, clipSupport, prepareCaptureCanvas, currentTransform]);

  /**
   * One tap: OS share sheet with the capture and the design's link (when a
   * signed-in user has one). Falls back to download + copy-link where the
   * browser can't hand files to the sheet. Camera pixels leave the device
   * only through these two explicit exits.
   */
  const sendToGroupChat = useCallback(async () => {
    if (!captured || !selected || sharing) return;
    setSharing(true);
    setShareNote(null);
    try {
      const url = (await resolveShareLink(selected)) ?? undefined;
      const outcome = await shareCapture({
        file: captured.file,
        text: buildShareText(selected.title),
        url,
      });
      if (outcome.kind === 'shared') {
        setShareNote({ kind: 'shared' });
      } else if (outcome.kind === 'fallback') {
        // No share sheet — the capture downloads and the link (if any) goes
        // to the clipboard, so the user can still paste both into the chat.
        downloadBlob(captured.file, captured.file.name);
        let linkCopied = false;
        if (url) {
          const { copyLinkToClipboard } = await import('@/services/ar/shareCapture');
          linkCopied = await copyLinkToClipboard(url);
        }
        setShareNote({ kind: 'fallback', linkCopied, hadLink: Boolean(url) });
      }
      // 'cancelled' — the user closed the sheet. Say nothing; they know.
    } catch {
      setShareNote({
        kind: 'error',
        message: "the hand-off didn't take — save it below and send it yourself.",
      });
    } finally {
      setSharing(false);
    }
  }, [captured, selected, sharing]);

  /** Plain local save — the other sanctioned exit. */
  const saveCapture = useCallback(() => {
    if (!captured) return;
    downloadBlob(captured.file, captured.file.name);
  }, [captured]);

  const handleExit = useCallback(() => {
    session.stop();
    onExit?.();
  }, [session, onExit]);

  const cycleGuide = useCallback(() => {
    setGuide((g) => nextGuide(g));
  }, []);

  const isLive = session.status === 'active';
  const isBusy = session.status === 'requesting' || session.status === 'starting';
  const hasFailed = session.status === 'error' || session.status === 'unsupported';
  const clipReady = clipSupport?.supported ?? false;

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-black">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-white/10 p-4 backdrop-blur-md">
        <button
          onClick={handleExit}
          className="text-xs font-bold uppercase tracking-widest text-white transition-colors hover:text-ducks-yellow"
        >
          <X size={18} />
        </button>
        <h2 className="rounded bg-ducks-green/10 px-2 py-1 font-mono text-xs font-bold uppercase tracking-widest text-ducks-green">
          Live Preview{placement ? ` // ${placement}` : ''}
        </h2>
        {/* Forward is a door too — trying it on should flow into matching,
            not dead-end at the X. */}
        {findArtistHref ? (
          <Link
            href={findArtistHref}
            className="text-xs font-bold uppercase tracking-widest text-ducks-yellow transition-colors hover:text-white"
          >
            Find your artist →
          </Link>
        ) : (
          <div className="w-8" />
        )}
      </div>

      {/* Stage */}
      <div
        ref={stageRef}
        className="relative flex flex-1 items-center justify-center overflow-hidden bg-black"
      >
        <video
          ref={videoRef}
          autoPlay
          playsInline
          muted
          className={`max-h-full max-w-full object-contain ${isLive ? '' : 'opacity-0'}`}
        />
        <canvas ref={captureCanvasRef} className="hidden" />

        {/* Idle — offer the camera */}
        {session.status === 'idle' && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-6 p-8 text-center">
            <Camera className="h-12 w-12 text-ducks-green" />
            <p className="max-w-sm text-sm text-gray-400">
              Point your camera at your skin. You place the design yourself — nothing is
              auto-detected, and what you see is what gets saved.
            </p>
            <button
              onClick={session.start}
              className="rounded-xl bg-ducks-green px-6 py-3 font-medium text-white transition-all hover:bg-ducks-green/90"
            >
              Start camera
            </button>
          </div>
        )}

        {isBusy && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-4">
            <Loader2 className="h-8 w-8 animate-spin text-ducks-green" />
            <p className="text-sm text-gray-400">
              {session.status === 'requesting' ? 'Waiting for camera permission…' : 'Starting camera…'}
            </p>
          </div>
        )}

        {/* Terminal failure — always says what went wrong and what to do */}
        {hasFailed && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-5 p-8 text-center">
            <AlertTriangle className="h-10 w-10 text-yellow-400" />
            <p className="max-w-sm text-sm text-gray-300">{session.message}</p>
            <div className="flex gap-3">
              {session.status === 'error' && (
                <button
                  onClick={session.start}
                  className="rounded-xl bg-white/10 px-5 py-2.5 text-sm text-white transition-all hover:bg-white/20"
                >
                  Try again
                </button>
              )}
              <button
                onClick={handleExit}
                className="rounded-xl bg-white/10 px-5 py-2.5 text-sm text-white transition-all hover:bg-white/20"
              >
                Go back
              </button>
            </div>
          </div>
        )}

        {/* Placement guide — a ruler on the glass, under the design. */}
        {isLive && <PlacementGuides guide={guide} />}

        {/* The on-skin guard firing */}
        {isLive && overlay.kind === 'blocked' && (
          <div className="absolute inset-x-4 top-4 z-10 rounded-lg border border-yellow-500/50 bg-yellow-500/90 px-4 py-3 backdrop-blur">
            <p className="flex items-start gap-2 text-sm font-medium text-black">
              <AlertTriangle size={16} className="mt-0.5 shrink-0" />
              <span>{overlay.verdict.message}</span>
            </p>
          </div>
        )}

        {/* The overlay itself */}
        {isLive && overlay.kind === 'ready' && (
          <img
            src={overlay.src}
            alt=""
            draggable={false}
            onPointerDown={onPointerDown}
            onPointerMove={onPointerMove}
            onPointerUp={onPointerUp}
            onPointerCancel={onPointerUp}
            className="absolute cursor-move select-none"
            style={{
              left: `${position.x}%`,
              top: `${position.y}%`,
              width: `${size}%`,
              opacity,
              transform: `translate(-50%, -50%) rotate(${rotation}deg)`,
              mixBlendMode: BLEND_MODE,
              touchAction: 'none',
            }}
          />
        )}

        {/* Recording pill — the only time the mirror talks over the stage. */}
        {isLive && recording && (
          <div className="absolute bottom-4 left-1/2 z-10 -translate-x-1/2 rounded-full bg-black/70 px-4 py-2 backdrop-blur">
            <p className="flex items-center gap-2 text-xs font-medium text-white">
              <span className="h-2 w-2 animate-pulse rounded-full bg-red-500" />
              rolling — hold it steady
            </p>
          </div>
        )}
      </div>

      {/* Controls */}
      {isLive && (
        <div className="border-t border-white/10 bg-black/80 p-4 backdrop-blur-xl">
          {overlay.kind === 'ready' && (
            <div className="mx-auto mb-4 max-w-2xl space-y-3">
              <Slider label="Size" min={10} max={100} value={size} onChange={setSize} />
              <Slider label="Rot" min={0} max={360} value={rotation} onChange={setRotation} />
              <Slider
                label="Ink"
                min={30}
                max={100}
                value={Math.round(opacity * 100)}
                onChange={(v) => setOpacity(v / 100)}
              />

              {/* Guides: opt-in scale reference. Off by default, always. */}
              <div className="flex items-center gap-3">
                <button
                  onClick={cycleGuide}
                  className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-medium transition-all ${
                    guide
                      ? 'border-ducks-green/60 bg-ducks-green/10 text-ducks-green'
                      : 'border-white/10 bg-white/5 text-gray-400 hover:border-white/30 hover:text-white'
                  }`}
                >
                  <Ruler size={14} />
                  guides: {guide ? guideById(guide).label : 'off'}
                </button>
                {guide && (
                  <p className="text-xs text-gray-400">{guideById(guide).hint}</p>
                )}
              </div>

              {/* Capture row — still always, clip where the browser can. */}
              <div className="flex gap-3">
                <button
                  onClick={captureStill}
                  disabled={recording}
                  className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-ducks-green px-4 py-3 text-sm font-medium text-white transition-all hover:bg-ducks-green/90 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  <Camera size={16} />
                  snap it
                </button>
                {clipReady && (
                  <button
                    onClick={captureClip}
                    disabled={recording}
                    className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-ducks-green/50 bg-ducks-green/10 px-4 py-3 text-sm font-medium text-ducks-green transition-all hover:bg-ducks-green/20 disabled:cursor-not-allowed disabled:opacity-40"
                  >
                    <Video size={16} />
                    {recording ? 'rolling…' : '3-sec clip'}
                  </button>
                )}
              </div>

              {captureError && (
                <p className="text-xs text-yellow-400" role="alert">
                  {captureError}
                </p>
              )}

              {/* The capture, waiting for its exit. Both doors are user taps. */}
              {captured && (
                <div className="rounded-xl border border-white/15 bg-white/5 p-3" role="status">
                  <p className="mb-3 text-xs text-gray-300">
                    {captured.kind === 'clip' ? 'got the clip.' : 'got the shot.'} send it to
                    the group chat — let them argue.
                  </p>
                  <div className="flex gap-3">
                    <button
                      onClick={sendToGroupChat}
                      disabled={sharing}
                      className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-ducks-yellow px-4 py-3 text-sm font-medium text-black transition-all hover:bg-ducks-yellow/90 disabled:cursor-not-allowed disabled:opacity-40"
                    >
                      <Share2 size={16} />
                      {sharing ? 'handing it off…' : 'send it to the group chat'}
                    </button>
                    <button
                      onClick={saveCapture}
                      className="flex items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm font-medium text-white transition-all hover:bg-white/20"
                    >
                      <Download size={16} />
                      save it
                    </button>
                  </div>
                  {shareNote?.kind === 'shared' && (
                    <p className="mt-3 text-xs text-ducks-green">
                      sent. now let them argue.
                    </p>
                  )}
                  {shareNote?.kind === 'fallback' && (
                    <p className="mt-3 text-xs text-gray-400">
                      no share sheet on this browser, so it downloaded instead —
                      {shareNote.hadLink
                        ? shareNote.linkCopied
                          ? ' and the design link is on your clipboard. paste both wherever the debate happens.'
                          : ' paste it wherever the debate happens.'
                        : ' paste it wherever the debate happens.'}
                    </p>
                  )}
                  {shareNote?.kind === 'error' && (
                    <p className="mt-3 text-xs text-yellow-400" role="alert">
                      {shareNote.message}
                    </p>
                  )}
                </div>
              )}

              {/* The next room in the funnel, right where conviction lands. */}
              {findArtistHref && (
                <Link
                  href={findArtistHref}
                  className="flex w-full items-center justify-center gap-2 rounded-xl border border-ducks-yellow/40 bg-ducks-yellow/10 px-4 py-3 text-sm font-medium text-ducks-yellow transition-all hover:bg-ducks-yellow/20"
                >
                  Find your artist →
                </Link>
              )}
            </div>
          )}

          {/* Design tray */}
          {designs.length === 0 ? (
            <p className="text-center text-xs text-gray-500">
              No generated designs yet — create one first, then come back.
            </p>
          ) : (
            <div className="hide-scrollbar flex gap-3 overflow-x-auto">
              {designs.map((d) => (
                <button
                  key={d.id}
                  onClick={() => setSelectedId(d.id)}
                  title={d.title ?? d.id}
                  className={`h-16 w-16 shrink-0 overflow-hidden rounded-xl border-2 transition-all ${
                    selectedId === d.id
                      ? 'scale-110 border-ducks-green'
                      : 'border-white/10 opacity-60 hover:border-white/30 hover:opacity-100'
                  }`}
                >
                  <img src={d.image} alt="" className="h-full w-full bg-white/5 object-contain" />
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function Slider({
  label,
  min,
  max,
  value,
  onChange,
}: {
  label: string;
  min: number;
  max: number;
  value: number;
  onChange: (v: number) => void;
}) {
  return (
    <div className="flex items-center gap-4">
      <span className="w-10 text-[10px] font-bold uppercase text-gray-400">{label}</span>
      <input
        type="range"
        min={min}
        max={max}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        aria-label={label}
        className="h-1 w-full cursor-pointer appearance-none rounded-lg bg-white/20 accent-ducks-green"
      />
    </div>
  );
}
