'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Camera, X, Download, AlertTriangle, Loader2 } from 'lucide-react';
import { useArSession } from '../useArSession';
import { prepareDesignForOverlay, type DesignSourceVerdict } from '@/services/ar/designSource';

/**
 * Live camera preview: point the phone at your skin, see the design on it.
 *
 * Deliberately NOT tracked. There is no body detection here and no fabricated
 * accuracy figure — the user positions the design themselves and what they see
 * is exactly what was composited. Body/limb tracking is a v2 concern (and no
 * library in this stack can do it today; see docs/adr/0021).
 *
 * Placement comes from the caller, which got it from intake. This component
 * never guesses which body part it is looking at.
 */

export interface ARMirrorDesign {
  id: string;
  /** Image URL of a design generated by the platform. */
  image: string;
  title?: string;
}

export interface ARMirrorProps {
  designs: ARMirrorDesign[];
  /** Placement tag resolved during intake. Displayed, never inferred. */
  placement?: string;
  onExit?: () => void;
}

/** Ink sinks into skin tone instead of floating like a sticker. */
const BLEND_MODE = 'multiply';

type OverlayState =
  | { kind: 'none' }
  | { kind: 'checking' }
  | { kind: 'ready'; src: string; verdict: DesignSourceVerdict }
  | { kind: 'blocked'; verdict: DesignSourceVerdict };

export default function ARMirror({ designs, placement, onExit }: ARMirrorProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const captureCanvasRef = useRef<HTMLCanvasElement | null>(null);
  const stageRef = useRef<HTMLDivElement | null>(null);

  const session = useArSession(videoRef);

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [overlay, setOverlay] = useState<OverlayState>({ kind: 'none' });
  const [position, setPosition] = useState({ x: 50, y: 50 }); // percent of stage
  const [size, setSize] = useState(40); // percent of stage width
  const [rotation, setRotation] = useState(0);
  const [opacity, setOpacity] = useState(0.85);
  const dragRef = useRef<{ x: number; y: number } | null>(null);

  const selected = useMemo(
    () => designs.find((d) => d.id === selectedId) ?? null,
    [designs, selectedId],
  );

  /**
   * Load the chosen design and run the on-skin guard before anything is drawn.
   * A design that fails the guard never produces a renderable source.
   */
  useEffect(() => {
    if (!selected) {
      setOverlay({ kind: 'none' });
      return;
    }

    let cancelled = false;
    setOverlay({ kind: 'checking' });

    const img = new Image();
    // Needed so the pixels are readable; without it the guard cannot inspect
    // the image and correctly refuses to render it.
    img.crossOrigin = 'anonymous';

    img.onload = () => {
      if (cancelled) return;
      const { verdict, canvas } = prepareDesignForOverlay(img);
      if (!canvas) {
        setOverlay({ kind: 'blocked', verdict });
        return;
      }
      setOverlay({ kind: 'ready', src: canvas.toDataURL('image/png'), verdict });
    };

    img.onerror = () => {
      if (cancelled) return;
      setOverlay({
        kind: 'blocked',
        verdict: {
          usable: false,
          reason: 'unreadable-pixels',
          whiteBorderFraction: null,
          message:
            "This design's image could not be loaded, so it can't be checked or previewed. Try again, or use the photo preview instead.",
        },
      });
    };

    img.src = selected.image;
    return () => {
      cancelled = true;
    };
  }, [selected]);

  // Dragging the design around the stage.
  const onPointerDown = useCallback((e: React.PointerEvent) => {
    e.preventDefault();
    (e.target as Element).setPointerCapture?.(e.pointerId);
    dragRef.current = { x: e.clientX, y: e.clientY };
  }, []);

  const onPointerMove = useCallback((e: React.PointerEvent) => {
    if (!dragRef.current || !stageRef.current) return;
    const rect = stageRef.current.getBoundingClientRect();
    const dx = ((e.clientX - dragRef.current.x) / rect.width) * 100;
    const dy = ((e.clientY - dragRef.current.y) / rect.height) * 100;
    dragRef.current = { x: e.clientX, y: e.clientY };
    setPosition((p) => ({
      x: Math.max(0, Math.min(100, p.x + dx)),
      y: Math.max(0, Math.min(100, p.y + dy)),
    }));
  }, []);

  const onPointerUp = useCallback(() => {
    dragRef.current = null;
  }, []);

  /** Flatten the current frame plus the overlay, exactly as shown. */
  const capture = useCallback(() => {
    const video = videoRef.current;
    const canvas = captureCanvasRef.current;
    if (!video || !canvas || overlay.kind !== 'ready') return;

    const w = video.videoWidth;
    const h = video.videoHeight;
    if (!w || !h) return;

    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    ctx.drawImage(video, 0, 0, w, h);

    const design = new Image();
    design.onload = () => {
      const drawW = (w * size) / 100;
      const drawH = drawW * (design.height / design.width || 1);
      const cx = (w * position.x) / 100;
      const cy = (h * position.y) / 100;

      ctx.save();
      ctx.globalAlpha = opacity;
      ctx.globalCompositeOperation = BLEND_MODE;
      ctx.translate(cx, cy);
      ctx.rotate((rotation * Math.PI) / 180);
      ctx.drawImage(design, -drawW / 2, -drawH / 2, drawW, drawH);
      ctx.restore();

      canvas.toBlob((blob) => {
        if (!blob) return;
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `tatt-ar-${Date.now()}.png`;
        link.click();
        URL.revokeObjectURL(url);
      }, 'image/png');
    };
    design.src = overlay.src;
  }, [overlay, size, position, rotation, opacity]);

  const handleExit = useCallback(() => {
    session.stop();
    onExit?.();
  }, [session, onExit]);

  const isLive = session.status === 'active';
  const isBusy = session.status === 'requesting' || session.status === 'starting';
  const hasFailed = session.status === 'error' || session.status === 'unsupported';

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-black">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-white/10 p-4 backdrop-blur-md">
        <button
          onClick={handleExit}
          className="text-xs font-bold uppercase tracking-widest text-white transition-colors hover:text-ducks-yellow"
        >
          <X size={18} />
        </button>
        <h2 className="rounded bg-ducks-green/10 px-2 py-1 font-mono text-xs font-bold uppercase tracking-widest text-ducks-green">
          Live Preview{placement ? ` // ${placement}` : ''}
        </h2>
        <div className="w-8" />
      </div>

      {/* Stage */}
      <div
        ref={stageRef}
        className="relative flex flex-1 items-center justify-center overflow-hidden bg-black"
      >
        <video
          ref={videoRef}
          autoPlay
          playsInline
          muted
          className={`max-h-full max-w-full object-contain ${isLive ? '' : 'opacity-0'}`}
        />
        <canvas ref={captureCanvasRef} className="hidden" />

        {/* Idle — offer the camera */}
        {session.status === 'idle' && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-6 p-8 text-center">
            <Camera className="h-12 w-12 text-ducks-green" />
            <p className="max-w-sm text-sm text-gray-400">
              Point your camera at your skin. You place the design yourself — nothing is
              auto-detected, and what you see is what gets saved.
            </p>
            <button
              onClick={session.start}
              className="rounded-xl bg-ducks-green px-6 py-3 font-medium text-white transition-all hover:bg-ducks-green/90"
            >
              Start camera
            </button>
          </div>
        )}

        {isBusy && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-4">
            <Loader2 className="h-8 w-8 animate-spin text-ducks-green" />
            <p className="text-sm text-gray-400">
              {session.status === 'requesting' ? 'Waiting for camera permission…' : 'Starting camera…'}
            </p>
          </div>
        )}

        {/* Terminal failure — always says what went wrong and what to do */}
        {hasFailed && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-5 p-8 text-center">
            <AlertTriangle className="h-10 w-10 text-yellow-400" />
            <p className="max-w-sm text-sm text-gray-300">{session.message}</p>
            <div className="flex gap-3">
              {session.status === 'error' && (
                <button
                  onClick={session.start}
                  className="rounded-xl bg-white/10 px-5 py-2.5 text-sm text-white transition-all hover:bg-white/20"
                >
                  Try again
                </button>
              )}
              <button
                onClick={handleExit}
                className="rounded-xl bg-white/10 px-5 py-2.5 text-sm text-white transition-all hover:bg-white/20"
              >
                Go back
              </button>
            </div>
          </div>
        )}

        {/* The on-skin guard firing */}
        {isLive && overlay.kind === 'blocked' && (
          <div className="absolute inset-x-4 top-4 z-10 rounded-lg border border-yellow-500/50 bg-yellow-500/90 px-4 py-3 backdrop-blur">
            <p className="flex items-start gap-2 text-sm font-medium text-black">
              <AlertTriangle size={16} className="mt-0.5 shrink-0" />
              <span>{overlay.verdict.message}</span>
            </p>
          </div>
        )}

        {/* The overlay itself */}
        {isLive && overlay.kind === 'ready' && (
          <img
            src={overlay.src}
            alt=""
            draggable={false}
            onPointerDown={onPointerDown}
            onPointerMove={onPointerMove}
            onPointerUp={onPointerUp}
            onPointerCancel={onPointerUp}
            className="absolute cursor-move select-none"
            style={{
              left: `${position.x}%`,
              top: `${position.y}%`,
              width: `${size}%`,
              opacity,
              transform: `translate(-50%, -50%) rotate(${rotation}deg)`,
              mixBlendMode: BLEND_MODE,
              touchAction: 'none',
            }}
          />
        )}
      </div>

      {/* Controls */}
      {isLive && (
        <div className="border-t border-white/10 bg-black/80 p-4 backdrop-blur-xl">
          {overlay.kind === 'ready' && (
            <div className="mx-auto mb-4 max-w-2xl space-y-3">
              <Slider label="Size" min={10} max={100} value={size} onChange={setSize} />
              <Slider label="Rot" min={0} max={360} value={rotation} onChange={setRotation} />
              <Slider
                label="Ink"
                min={30}
                max={100}
                value={Math.round(opacity * 100)}
                onChange={(v) => setOpacity(v / 100)}
              />
              <button
                onClick={capture}
                className="flex w-full items-center justify-center gap-2 rounded-xl bg-ducks-green px-4 py-3 text-sm font-medium text-white transition-all hover:bg-ducks-green/90"
              >
                <Download size={16} />
                Save this view
              </button>
            </div>
          )}

          {/* Design tray */}
          {designs.length === 0 ? (
            <p className="text-center text-xs text-gray-500">
              No generated designs yet — create one first, then come back.
            </p>
          ) : (
            <div className="hide-scrollbar flex gap-3 overflow-x-auto">
              {designs.map((d) => (
                <button
                  key={d.id}
                  onClick={() => setSelectedId(d.id)}
                  title={d.title ?? d.id}
                  className={`h-16 w-16 shrink-0 overflow-hidden rounded-xl border-2 transition-all ${
                    selectedId === d.id
                      ? 'scale-110 border-ducks-green'
                      : 'border-white/10 opacity-60 hover:border-white/30 hover:opacity-100'
                  }`}
                >
                  <img src={d.image} alt="" className="h-full w-full bg-white/5 object-contain" />
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function Slider({
  label,
  min,
  max,
  value,
  onChange,
}: {
  label: string;
  min: number;
  max: number;
  value: number;
  onChange: (v: number) => void;
}) {
  return (
    <div className="flex items-center gap-4">
      <span className="w-10 text-[10px] font-bold uppercase text-gray-400">{label}</span>
      <input
        type="range"
        min={min}
        max={max}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        aria-label={label}
        className="h-1 w-full cursor-pointer appearance-none rounded-lg bg-white/20 accent-ducks-green"
      />
    </div>
  );
}
